[version]
path = "src/finite_difference/__init__.py"

[envs.default]
features = ["test"]

[envs.default.scripts]
# --cov must not come before an argument in order to use the sources defined by config
cov = "pytest --cov --cov-report=term-missing --cov-config=pyproject.toml {args}"
doctest = "pytest --cov --doctest-modules --doctest-continue-on-failure {args}"

[[envs.test.matrix]]
python = ["3.10", "3.11"]

[envs.lint]
features = ["lint"]
detached = true

[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/finite_difference tests}"
check = [
    "ruff {args:.}",
    "black --check --diff {args:.}"
]
format = [
    "black {args:.}",
    "ruff --fix {args:.}"
]
all = [
    "format",
    "typing"
]

[envs.docs]
features = ["docs"]

[envs.docs.scripts]
build = "mkdocs build --clean --strict"
serve = "mkdocs serve --dev-addr localhost:8000"
