[version]
path = "src/finite_difference/__init__.py"

[envs.default]
dependencies = [
    "pytest",
    "pytest-cov",
]
[envs.default.scripts]
# --cov must not come before an argument in order to use the sources defined by config
cov = "pytest --cov --cov-report=term-missing --cov-config=pyproject.toml {args}"
doctest = "pytest --cov --doctest-modules --doctest-continue-on-failure --ignore=docs {args}"

[[envs.test.matrix]]
python = ["310", "311"]

[envs.style]
detached = true
dependencies = [
    "black",
    "isort",
]

[envs.style.scripts]
check = [
    "black --check --diff .",
    "isort --check-only --diff .",
]
format = [
    "isort .",
    "black .",
]

[envs.docs]
features = ["docs"]

[envs.docs.scripts]
build = "mkdocs build --clean --strict"
serve = "mkdocs serve --dev-addr localhost:8000"
