site_name: finite-difference
site_url: https://finite-difference.readthedocs.io/
site_description: Numerical derivatives using Python.
site_author: Robert Grzonka
repo_name: Rastow/finite-difference
repo_url: https://github.com/Rastow/finite-difference/
edit_uri: blob/master/docs/
copyright: Copyright &copy; 2022 Robert Grzonka

theme:
  name: material
  icon:
    edit: material/file-edit-outline
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: teal
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            members_order: source
            show_signature_annotations: true
            show_source: false
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - http://docs.scipy.org/doc/scipy/objects.inv

nav:
  - Home: index.md
  - Code Reference: reference/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Rastow
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/Rastow/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrRastow
    - icon: fontawesome/solid/paper-plane
      link: mailto:<robert.grzonka@fau.de>

watch:
  - src
