[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "finite-difference"
description = 'Numerical derivatives.'
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-3-Clause"
keywords = [
    "derivative",
    "differentiation",
    "numerics"
]
authors = [
    { name = "Robert Grzonka", email = "robert.grzonka@fau.de" },
]
maintainers = [
    { name = "Robert Grzonka", email = "robert.grzonka@fau.de" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = [
    "numpy"
]
dynamic = ["version"]

[project.optional-dependencies]
docs = [
    "mkdocs>=1.4",
    "mkdocs-gen-files>=0.4",
    "mkdocs-literate-nav>=0.5",
    "mkdocstrings[python]>=0.19"
]

[project.urls]
Documentation = "https://finite-difference.readthedocs.io/"
Tracker = "https://github.com/Rastow/finite-difference/issues"
Source = "https://github.com/Rastow/finite-difference"

[tool.coverage.run]
branch = true
parallel = true

[tool.isort]
profile = "black"
