[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "finite-difference"
description = 'Numerical derivatives.'
readme = "README.md"
requires-python = ">=3.10"
license = "BSD-3-Clause"
keywords = [
    "derivative",
    "differentiation",
    "numerics"
]
authors = [
    { name = "Robert Grzonka", email = "robert.grzonka@fau.de" },
]
maintainers = [
    { name = "Robert Grzonka", email = "robert.grzonka@fau.de" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = []
dynamic = ["version"]

[project.urls]
Documentation = "https://finite-difference.readthedocs.io/"
Tracker = "https://github.com/Rastow/finite-difference/issues"
Source = "https://github.com/Rastow/finite-difference"

[tool.hatch.version]
path = "src/finite_difference/__init__.py"

[tool.hatch.envs.default]
dependencies = [
    "pytest",
    "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src/finite_difference --cov=tests {args}"

[[tool.hatch.envs.test.matrix]]
python = ["310", "311"]

[tool.coverage.run]
branch = true
parallel = true
